# This is for a MSYS2 version running on Windows. It should build ok either 32 or 64 bit. Only been checked on a Windows 11 system.

HOST_CPU = 
DELIM = '
PiOS32 = 0
LINUX = 0
MSYS2 = 1
MINGW = 0
EXTRA_DEFINES = -DMSYS2
EXTRA_CHKS =
DBG = 
OPT = -O2
CC = gcc
ECHO = echo
RM = rm -f 
RMDIR = rm -rf

include Makefile.common




