# This is for a generic Linux build without readline library.

HOST_CPU = 
DELIM = '
PiOS32 = 1
LINUX = 1
MSYS2 = 0
MINGW = 0
EXTRA_DEFINES = -D_ISOC99_SOURCE #-DUSE_READLINE
EXTRA_CHKS =
EXTRA_LIBS = #-lreadline
DBG = 
OPT = -O2
CC = gcc
ECHO = /bin/echo -e
RM = rm -f 

include Makefile.common

