# Only tested on a Pi5 running 32 bit O/S. It should build and run on either 32 or 64 bit.

HOST_CPU = 
DELIM = '
PiOS32 = 1
LINUX = 1
MSYS2 = 0
MINGW = 0
EXTRA_DEFINES =
EXTRA_CHKS =
DBG = 
OPT = -O
CC = gcc
ECHO = /bin/echo -e

include Makefile.common
